/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package controle;

import controle.frm_Login;
import controle.frm_LoginFun;
/**
 *
 * @author kolye
 */
public class frm_Menu extends javax.swing.JFrame {

    /**
     * Creates new form frm_Menu
     */
    public frm_Menu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rotulo = new javax.swing.JLabel();
        btn_logincliente = new javax.swing.JButton();
        btn_loginfuncionario = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        rotulo1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        rotulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        rotulo.setForeground(new java.awt.Color(255, 255, 255));
        rotulo.setText("Menu de Acesso");
        jPanel1.add(rotulo);
        rotulo.setBounds(330, 330, 280, 60);

        btn_logincliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_logincliente.setText("Login Cliente");
        btn_logincliente.setFocusable(false);
        btn_logincliente.setRequestFocusEnabled(false);
        btn_logincliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginclienteActionPerformed(evt);
            }
        });
        jPanel1.add(btn_logincliente);
        btn_logincliente.setBounds(240, 410, 140, 50);

        btn_loginfuncionario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_loginfuncionario.setText("Login Gerencial");
        btn_loginfuncionario.setFocusable(false);
        btn_loginfuncionario.setRequestFocusEnabled(false);
        btn_loginfuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginfuncionarioActionPerformed(evt);
            }
        });
        jPanel1.add(btn_loginfuncionario);
        btn_loginfuncionario.setBounds(510, 410, 160, 50);

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/door_in.png"))); // NOI18N
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        jPanel1.add(btnSair);
        btnSair.setBounds(1320, 720, 30, 30);

        rotulo1.setBackground(new java.awt.Color(0, 0, 0));
        rotulo1.setFont(new java.awt.Font("Segoe UI", 1, 65)); // NOI18N
        rotulo1.setForeground(new java.awt.Color(255, 255, 255));
        rotulo1.setText("Dream Fantasy");
        jPanel1.add(rotulo1);
        rotulo1.setBounds(240, 250, 470, 110);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/telasacesso/acesso1.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1366, 770);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginclienteActionPerformed
        frm_Login logincliente = new frm_Login();
        logincliente.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_loginclienteActionPerformed

    private void btn_loginfuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginfuncionarioActionPerformed
        frm_LoginFun loginfuncionario = new frm_LoginFun();
        loginfuncionario.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_loginfuncionarioActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnSair;
    public javax.swing.JButton btn_logincliente;
    public javax.swing.JButton btn_loginfuncionario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel rotulo;
    public javax.swing.JLabel rotulo1;
    // End of variables declaration//GEN-END:variables
}
