/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package controle;

import controle.frm_Login;

/**
 *
 * @author Admin
 */
public class frm_cadastrar extends javax.swing.JFrame {

    /**
     * Creates new form frm_cadastrar
     */
    public frm_cadastrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        rotulo1 = new javax.swing.JLabel();
        rotulo4 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        txt10 = new javax.swing.JTextField();
        cadastrar = new javax.swing.JButton();
        rotulo2 = new javax.swing.JLabel();
        txt3 = new javax.swing.JTextField();
        rotulo3 = new javax.swing.JLabel();
        txt4 = new javax.swing.JTextField();
        rotulo5 = new javax.swing.JLabel();
        rotulo6 = new javax.swing.JLabel();
        rotulo7 = new javax.swing.JLabel();
        rotulo8 = new javax.swing.JLabel();
        rotulo9 = new javax.swing.JLabel();
        txt5 = new javax.swing.JTextField();
        txt6 = new javax.swing.JTextField();
        txt7 = new javax.swing.JTextField();
        txt8 = new javax.swing.JTextField();
        txt9 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(170, 83, 196));
        jPanel1.setLayout(null);

        titulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("Cadastro");
        jPanel1.add(titulo);
        titulo.setBounds(200, 40, 150, 40);

        rotulo1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rotulo1.setForeground(new java.awt.Color(255, 255, 255));
        rotulo1.setText("Nome:");
        jPanel1.add(rotulo1);
        rotulo1.setBounds(70, 130, 50, 20);

        rotulo4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rotulo4.setForeground(new java.awt.Color(255, 255, 255));
        rotulo4.setText("CPF/CNPJ:");
        jPanel1.add(rotulo4);
        rotulo4.setBounds(70, 280, 80, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Senha:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(70, 580, 50, 20);
        jPanel1.add(txt1);
        txt1.setBounds(130, 130, 320, 22);
        jPanel1.add(txt2);
        txt2.setBounds(130, 180, 320, 22);
        jPanel1.add(txt10);
        txt10.setBounds(130, 580, 290, 22);

        cadastrar.setText("Cadastrar");
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(cadastrar);
        cadastrar.setBounds(220, 640, 90, 25);

        rotulo2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rotulo2.setForeground(new java.awt.Color(255, 255, 255));
        rotulo2.setText("Email:");
        jPanel1.add(rotulo2);
        rotulo2.setBounds(70, 180, 40, 20);
        jPanel1.add(txt3);
        txt3.setBounds(220, 230, 230, 22);

        rotulo3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rotulo3.setForeground(new java.awt.Color(255, 255, 255));
        rotulo3.setText("Data de Nascimento:");
        jPanel1.add(rotulo3);
        rotulo3.setBounds(70, 230, 140, 20);
        jPanel1.add(txt4);
        txt4.setBounds(150, 280, 240, 22);

        rotulo5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rotulo5.setForeground(new java.awt.Color(255, 255, 255));
        rotulo5.setText("Endereço:");
        jPanel1.add(rotulo5);
        rotulo5.setBounds(70, 330, 80, 20);

        rotulo6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rotulo6.setForeground(new java.awt.Color(255, 255, 255));
        rotulo6.setText("CEP:");
        jPanel1.add(rotulo6);
        rotulo6.setBounds(70, 380, 40, 20);

        rotulo7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rotulo7.setForeground(new java.awt.Color(255, 255, 255));
        rotulo7.setText("Bairro:");
        jPanel1.add(rotulo7);
        rotulo7.setBounds(70, 430, 50, 20);

        rotulo8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rotulo8.setForeground(new java.awt.Color(255, 255, 255));
        rotulo8.setText("Cidade:");
        jPanel1.add(rotulo8);
        rotulo8.setBounds(70, 480, 60, 20);

        rotulo9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rotulo9.setForeground(new java.awt.Color(255, 255, 255));
        rotulo9.setText("Estado:");
        jPanel1.add(rotulo9);
        rotulo9.setBounds(70, 530, 60, 20);
        jPanel1.add(txt5);
        txt5.setBounds(150, 330, 300, 22);
        jPanel1.add(txt6);
        txt6.setBounds(110, 380, 240, 22);
        jPanel1.add(txt7);
        txt7.setBounds(130, 430, 320, 22);
        jPanel1.add(txt8);
        txt8.setBounds(140, 480, 310, 22);
        jPanel1.add(txt9);
        txt9.setBounds(130, 530, 130, 22);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        frm_Login mostralogin = new frm_Login();
        mostralogin.setVisible(true);
        dispose();
    }//GEN-LAST:event_cadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_cadastrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton cadastrar;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JLabel rotulo1;
    public javax.swing.JLabel rotulo2;
    public javax.swing.JLabel rotulo3;
    public javax.swing.JLabel rotulo4;
    public javax.swing.JLabel rotulo5;
    public javax.swing.JLabel rotulo6;
    public javax.swing.JLabel rotulo7;
    public javax.swing.JLabel rotulo8;
    public javax.swing.JLabel rotulo9;
    public javax.swing.JLabel titulo;
    public javax.swing.JTextField txt1;
    public javax.swing.JTextField txt10;
    public javax.swing.JTextField txt2;
    public javax.swing.JTextField txt3;
    public javax.swing.JTextField txt4;
    public javax.swing.JTextField txt5;
    public javax.swing.JTextField txt6;
    public javax.swing.JTextField txt7;
    public javax.swing.JTextField txt8;
    public javax.swing.JTextField txt9;
    // End of variables declaration//GEN-END:variables
}
