/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package controle;

import conexao.Conexao; // importar do package a classe
import javax.swing.JOptionPane;
import java.sql.*; // para reconhecimento dos comandos SQL
import controle.frm_Login;
import controle.frm_Menu;

/**
 *
 * @author Admin
 */
public class frm_cadastrar extends javax.swing.JFrame {
    
    Conexao con_cliente;

    public frm_cadastrar() {
        initComponents();
        setLocationRelativeTo( null );
        con_cliente = new Conexao(); // inicialização do objeto como instância
        con_cliente.conecta(); // chama o método que conecta
        con_cliente.executaSQL("select * from clientes order by id_cli");


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        rotulo1 = new javax.swing.JLabel();
        rotulo4 = new javax.swing.JLabel();
        rotulo11 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        txt10 = new javax.swing.JTextField();
        cadastrar = new javax.swing.JButton();
        rotulo2 = new javax.swing.JLabel();
        txt3 = new javax.swing.JTextField();
        rotulo3 = new javax.swing.JLabel();
        txt4 = new javax.swing.JTextField();
        rotulo5 = new javax.swing.JLabel();
        rotulo6 = new javax.swing.JLabel();
        rotulo7 = new javax.swing.JLabel();
        rotulo8 = new javax.swing.JLabel();
        rotulo9 = new javax.swing.JLabel();
        txt5 = new javax.swing.JTextField();
        txt6 = new javax.swing.JTextField();
        txt7 = new javax.swing.JTextField();
        txt8 = new javax.swing.JTextField();
        txt9 = new javax.swing.JTextField();
        rotulo10 = new javax.swing.JLabel();
        combobox = new javax.swing.JComboBox<>();
        rotulo12 = new javax.swing.JLabel();
        txt11 = new javax.swing.JTextField();
        rotulo13 = new javax.swing.JLabel();
        txt12 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(170, 83, 196));
        jPanel1.setLayout(null);

        titulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("Cadastro");
        jPanel1.add(titulo);
        titulo.setBounds(200, 40, 150, 40);

        rotulo1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rotulo1.setForeground(new java.awt.Color(255, 255, 255));
        rotulo1.setText("Nome:");
        jPanel1.add(rotulo1);
        rotulo1.setBounds(70, 130, 50, 20);

        rotulo4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rotulo4.setForeground(new java.awt.Color(255, 255, 255));
        rotulo4.setText("CPF/CNPJ:");
        jPanel1.add(rotulo4);
        rotulo4.setBounds(70, 280, 80, 20);

        rotulo11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rotulo11.setForeground(new java.awt.Color(255, 255, 255));
        rotulo11.setText("Senha:");
        jPanel1.add(rotulo11);
        rotulo11.setBounds(70, 680, 50, 20);
        jPanel1.add(txt1);
        txt1.setBounds(130, 130, 320, 22);
        jPanel1.add(txt2);
        txt2.setBounds(130, 180, 320, 22);
        jPanel1.add(txt10);
        txt10.setBounds(140, 630, 290, 22);

        cadastrar.setText("Cadastrar");
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(cadastrar);
        cadastrar.setBounds(220, 810, 90, 25);

        rotulo2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rotulo2.setForeground(new java.awt.Color(255, 255, 255));
        rotulo2.setText("Email:");
        jPanel1.add(rotulo2);
        rotulo2.setBounds(70, 180, 40, 20);
        jPanel1.add(txt3);
        txt3.setBounds(220, 230, 230, 22);

        rotulo3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rotulo3.setForeground(new java.awt.Color(255, 255, 255));
        rotulo3.setText("Data de Nascimento:");
        jPanel1.add(rotulo3);
        rotulo3.setBounds(70, 230, 140, 20);
        jPanel1.add(txt4);
        txt4.setBounds(150, 280, 240, 22);

        rotulo5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rotulo5.setForeground(new java.awt.Color(255, 255, 255));
        rotulo5.setText("Endereço:");
        jPanel1.add(rotulo5);
        rotulo5.setBounds(70, 330, 80, 20);

        rotulo6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rotulo6.setForeground(new java.awt.Color(255, 255, 255));
        rotulo6.setText("CEP:");
        jPanel1.add(rotulo6);
        rotulo6.setBounds(70, 380, 40, 20);

        rotulo7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rotulo7.setForeground(new java.awt.Color(255, 255, 255));
        rotulo7.setText("Bairro:");
        jPanel1.add(rotulo7);
        rotulo7.setBounds(70, 430, 50, 20);

        rotulo8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rotulo8.setForeground(new java.awt.Color(255, 255, 255));
        rotulo8.setText("Cidade:");
        jPanel1.add(rotulo8);
        rotulo8.setBounds(70, 480, 60, 20);

        rotulo9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rotulo9.setForeground(new java.awt.Color(255, 255, 255));
        rotulo9.setText("Estado:");
        jPanel1.add(rotulo9);
        rotulo9.setBounds(70, 530, 60, 20);
        jPanel1.add(txt5);
        txt5.setBounds(150, 330, 300, 22);
        jPanel1.add(txt6);
        txt6.setBounds(110, 380, 240, 22);
        jPanel1.add(txt7);
        txt7.setBounds(130, 430, 320, 22);
        jPanel1.add(txt8);
        txt8.setBounds(140, 480, 310, 22);
        jPanel1.add(txt9);
        txt9.setBounds(130, 530, 130, 22);

        rotulo10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rotulo10.setForeground(new java.awt.Color(255, 255, 255));
        rotulo10.setText("Tipo:");
        jPanel1.add(rotulo10);
        rotulo10.setBounds(70, 580, 60, 20);

        combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PF", "PJ", "ONG" }));
        jPanel1.add(combobox);
        combobox.setBounds(120, 580, 54, 22);

        rotulo12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rotulo12.setForeground(new java.awt.Color(255, 255, 255));
        rotulo12.setText("Apelido:");
        jPanel1.add(rotulo12);
        rotulo12.setBounds(70, 630, 60, 20);
        jPanel1.add(txt11);
        txt11.setBounds(130, 680, 290, 22);

        rotulo13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rotulo13.setForeground(new java.awt.Color(255, 255, 255));
        rotulo13.setText("Telefone:");
        jPanel1.add(rotulo13);
        rotulo13.setBounds(70, 730, 70, 20);
        jPanel1.add(txt12);
        txt12.setBounds(140, 730, 290, 22);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/door_in.png"))); // NOI18N
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        jPanel2.add(btnSair);
        btnSair.setBounds(479, 850, 30, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 892, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        String nome_cli = txt1.getText();
        String email_cli = txt2.getText();
        String data_nasc_cli = txt3.getText();
        String cpf_cnpj = txt4.getText();
        String endereco_cli = txt5.getText();
        String cep_cli = txt6.getText();
        String bairro_cli = txt7.getText();
        String cidade_cli = txt8.getText();
        String estado_cli = txt9.getText();
        String tipo_cli = combobox.getSelectedItem().toString();
        String apelido_nome_fantasia = txt10.getText();
        String senha_cli = txt11.getText();
        String telefone_cli = txt12.getText();
        
        try {
            String insert_sql="insert into clientes (email_cli,senha_cli,nome_cli,data_nasc_cli,cep_cli,endereco_cli,bairro_cli,cidade_cli,telefone_cli,cpf_cnpj,estado_cli,apelido_nome_fantasia,tipo) values ('" + email_cli + "','" + senha_cli + "','" + nome_cli + "', '" + data_nasc_cli + "','" + cep_cli + "','" + endereco_cli + "', '" + bairro_cli + "','" + cidade_cli + "', '" + telefone_cli + "', '" + cpf_cnpj + "', '" + estado_cli + "', '" + apelido_nome_fantasia + "','" + tipo_cli + "')";
            System.out.println(insert_sql);
            con_cliente.statement.executeUpdate(insert_sql);
            JOptionPane.showMessageDialog(null,"Gravação realizada com sucesso!!","Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
            //con_cliente.executaSQL("select * from clientes order by id_cli");
            //con_cliente.resultset.first();

            
        }catch(SQLException errosql) {
            JOptionPane.showMessageDialog(null,"\n Erro na gravação :\n "+errosql,"Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
        }
               
        frm_Login mostralogin = new frm_Login();
        mostralogin.setVisible(true);
        dispose();
    }//GEN-LAST:event_cadastrarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        frm_Menu mostramenu = new frm_Menu();
        mostramenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_cadastrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnSair;
    public javax.swing.JButton cadastrar;
    public javax.swing.JComboBox<String> combobox;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JLabel rotulo1;
    public javax.swing.JLabel rotulo10;
    public javax.swing.JLabel rotulo11;
    public javax.swing.JLabel rotulo12;
    public javax.swing.JLabel rotulo13;
    public javax.swing.JLabel rotulo2;
    public javax.swing.JLabel rotulo3;
    public javax.swing.JLabel rotulo4;
    public javax.swing.JLabel rotulo5;
    public javax.swing.JLabel rotulo6;
    public javax.swing.JLabel rotulo7;
    public javax.swing.JLabel rotulo8;
    public javax.swing.JLabel rotulo9;
    public javax.swing.JLabel titulo;
    public javax.swing.JTextField txt1;
    public javax.swing.JTextField txt10;
    public javax.swing.JTextField txt11;
    public javax.swing.JTextField txt12;
    public javax.swing.JTextField txt2;
    public javax.swing.JTextField txt3;
    public javax.swing.JTextField txt4;
    public javax.swing.JTextField txt5;
    public javax.swing.JTextField txt6;
    public javax.swing.JTextField txt7;
    public javax.swing.JTextField txt8;
    public javax.swing.JTextField txt9;
    // End of variables declaration//GEN-END:variables
}
